# Generated by Django 2.2.3 on 2019-07-26 20:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_name', models.TextField(primary_key=True, serialize=False)),
                ('catalog_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeometryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='FriendlyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', django.contrib.postgres.fields.hstore.HStoreField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Catalog')),
                ('parent_geometry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.GeometryStore')),
            ],
        ),
    ]
